version: '3'
services:
  pact-broker:
    container_name: pact_broker
    image: 'dius/pact-broker'
    depends_on:
      - db
#    links:
#      - db
    environment:
      PACT_BROKER_DATABASE_ADAPTER: postgres
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: 1234
      PACT_BROKER_DATABASE_HOST: db
      PACT_BROKER_DATABASE_PORT: 5432
      PACT_BROKER_DATABASE_NAME: dbdev
    ports:
      - "8000:80"
  db:
    image: 'postgres'
#    restart: always
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: dbdev